AllCops:
  Exclude:
    - 'lib/active_storage_drag_and_drop/version.rb'
    - 'test/dummy/db/migrate/*'
    - 'test/dummy/bin/*'
    - 'test/dummy/config/**/*'

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Metrics/LineLength:
  Max: 99

Metrics/BlockLength:
  Exclude:
    - 'active_storage_drag_and_drop.gemspec'
